version: "3.8"

services:
  api:
    ports: []
    networks:
      - evolution-net

  frontend:
    ports: []
    networks:
      - evolution-net

  redis:
    networks:
      evolution-net:
        aliases:
          - evolution-redis

  evolution-postgres:
    networks:
      - evolution-net

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
